version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn --reload --host 0.0.0.0 --port 8000 start:create_app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}